 # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest  
    # ON which machine our project will work.

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    # this command tell to check the  current branch, by defauult it checkout main branch
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      # This command is just teling to setup nodejs environment before doing anything else and its optional
    
      with:
        node-version: ${{ matrix.node-version }}
        # Also we need to setup of other node version also
        cache: 'npm'
    - name: "installing Dependencies"   
      run: npm i
    - name: "Build command"
      run: npm run build --if-present
  